### ISSUE TITLE
Is it a self-supervised method?

### ISSUE THREAD

**Issue by wenbinTse** [XiaohangZhan/conditional-motion-propagation#3]
Thanks for your interesting work.
I have a small question. The paper title implies your method  is self-supervised, but I notice your network is supervised by ground truth which is generated by another optical flow network.
So is it proper to be called as a self-supervised method?

**Comment by XiaohangZhan** [comment]
Optical flow is the information originally contained in the video data itself, rather than from manual annotations. In my understanding, it is self-supervised. Besides, there are also self-supervised optical flow estimation methods.

**Comment by wenbinTse** [comment]
But you use an optical flow network, which is trained with manual annotations, to generate your supervisions. I think it's a little strange.

**Comment by XiaohangZhan** [comment]
I understand your concerns. In my opinion, self-supervision is not equivalent to learning from pure images without any supervision. The key point lies in whether we directly supervise the concept to learn. In this work, we are not aim at learning optical flow. The concept to learn is objectness and kinematic properties. We do not have the annotations for this concept. Hence, it is intrinsically different from supervised learning that directly learns concepts from manual annotations.
Besides, the network we used for optical flow is trained on synthetic data rather than manual annotations. We choose LiteFlowNet in our experiments just for efficiency, otherwise it would cost a very very long time to extract optical flows from million level image pairs. CMP is also compatible with other unsupervised optical flow estimation methods. Using which optical flow estimation method does not affect the main idea or the methodology of CMP.

**Comment by SiminKou** [comment]
How did you get the initial guidance here? The article says that the guidance is sampled from the target flow, but what is the basis of the "sparse motion+mask" we input at the beginning? At this time, the static image does not have a corresponding optical flow diagram.
